<?php $this->headTitle('Home'); ?>

<div class="row">
    <div class="col-md-12">
        <h2>Database Records</h2>
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <th>Date/Time</th>
                <th>Measurement</th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($this->measurements)): ?>
            <?php foreach($this->measurements as $measurement): ?>
            <tr>
                <td><?= $measurement['date_time']; ?></td>
                <td><?= $measurement['temp']; ?></td>
            </tr>
            <?php endforeach; ?>
            <?php else: ?>
            <tr><td colspan="2">No records available</td></tr>
            <?php endif; ?>
            </tbody>
            <tfoot>
            <tr><td colspan="2">Records: <?= count($this->measurements); ?></td></tr>
            </tfoot>
        </table>
    </div>
</div>
